version: 2

sources:
  - name: dev_gilberto
    tables:
      - name: agencias
        description: 'Tabela de informações das agências'
        columns:
          - name: cod_agencia 
            tests:
              - unique
              - not_null

      - name: clientes
        description: 'Tabela de informações de clientes'
        columns:
          - name: cod_cliente 
            tests:
              - unique
              - not_null

      - name: colaborador_agencia
        description: 'Relacionamento entre colaboradores e agências'
        columns:
          - name: cod_colaborador
            tests:
              - unique
          - name: cod_agencia
            tests:
              - not_null

      - name: colaboradores
        description: 'Tabela de informações dos colaboradores'
        columns:
          - name: cod_colaborador
            tests:
              - unique
              - not_null
            
      - name: contas
        description: 'Tabela de informações de contas dos clientes'
        columns:
          - name: num_conta
            tests:
              - unique
              - not_null
          - name: cod_cliente
            tests:
              - not_null
          - name: cod_agencia
            tests:
              - not_null
          - name: cod_colaborador
            tests:
              - not_null

      - name: propostas_credito
        description: 'Tabela de propostas de crédito aos clientes'
        columns:
          - name: cod_proposta
            tests:
              - unique
              - not_null
          - name: cod_cliente
            tests:
              - not_null

      - name: transacoes
        description: 'Tabela de transações financeiras'
        columns:
          - name: cod_transacao
            tests:
              - unique
              - not_null
          - name: num_conta
            tests:
              - not_null